import "./styles/globals.css";
import type { Metadata } from "next";
import { Jost } from "next/font/google";
import MainNavigation from "./components/main-navigation";

import { Providers as ReduxProvider } from "./redux/provider";
import { Providers } from "./providers";

const inter = Jost({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Pets Paw",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          <main>
            <MainNavigation />

            <section>
              <ReduxProvider>{children}</ReduxProvider>
            </section>
          </main>
        </Providers>
      </body>
    </html>
  );
}
