import "./styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import MainNavigation from "./components/main-navigation";

import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pets Paw",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          <main>
            <MainNavigation />
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
